language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - phpenv config-rm xdebug.ini

install:
  - travis_retry composer install --prefer-source --no-interaction --no-progress --no-suggest

before_script:
  - composer self-update
  - travis_retry composer update --prefer-source --no-interaction --no-progress --no-suggest

script:
  - vendor/bin/phpunit